# Generated by Django 4.0.5 on 2022-06-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_statement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
